### ISSUE TITLE
MarkBind Docs issue

### ISSUE THREAD

**Issue by tlylt** [AY2324S1-CS2103T-T15-3/tp#2]
Hi Team (@revdrag),

I'm a MarkBind dev checking in to see if the MarkBind docs branch is working well for CS2103T students. I noticed that even though you have updated the repo name in docs.yml in https://github.com/AY2324S1-CS2103T-T15-3/tp/commit/955486fb054cd4a14768a59ee37c36003903a30d, the published site seems to have some issues due to incorrect baseUrl.
- https://ay2324s1-cs2103t-t15-3.github.io/tp/
- The problem is that some web assets are not fetched correctly, hence the rendering is incorrect

**You will need to update the baseUrl in docs.yml to '/tp' (the actual name of this github repo), instead of your organization name to make the reference work as expected when published via GitHub pages. That will make the rendering work.**

E.g.
![image](https://github.com/AY2324S1-CS2103T-T15-3/tp/assets/41845017/8b3585cd-05b5-481b-88ab-07fae467ba1c)

cc @damithc

**Comment by revdrag** [comment]
Hi @tlylt,

I have pushed the commit and the rendering of the website seems to work properly now. Thanks for pointing it out. Also, in the site.json file, do I have the make the same changes to "baseUrl"?

**Comment by tlylt** [comment]
> Hi @tlylt,
> 
> I have pushed the commit and the rendering of the website seems to work properly now. Thanks for pointing it out. Also, in the site.json file, do I have the make the same changes to "baseUrl"?

Nope that's fine, just leave it as is. This is different because when you publish to GitHub pages you have to publish to the path associated with the repo, hence it's like a sub-path that needs to be configured properly. When you run the site locally there's no such issue.

Great work! It's working fine now :)
