### ISSUE TITLE
Student's attendance exceed lesson's attendance

### ISSUE THREAD

**Issue by seanpzk** [AY2324S1-CS2103T-T15-3/tp#83]
Steps to reproduce:
1. Add a `Class`
2. Add a `Student` into the `Class`
3. Mark `Student` as Present

![image](https://github.com/AY2324S1-CS2103T-T15-3/tp/assets/122248828/5a5799e2-e2dc-4118-b6e5-0ef0e2c90028)

**Comment by DonovanJJ** [comment]
Situation: The total lessons and class lessons were not integrated well together
Fix: Added conditional statement to verify if after it will cause any problem if the command goes through
