### ISSUE TITLE
[PE-D][Tester E] Error message for add - invalid command 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T15-3/tp#93]
When typing an invalid format for add, the error message does not seem relevant as shown below: 

![image.png](https://raw.githubusercontent.com/tayruxin/ped/main/files/3727ba59-38ee-4583-85a8-c0f2a1d793ae.png)

Perhaps can consider giving more relevant examples for the error message such as "add c/ cs2103t". The description of the feature does not fix the context of the application 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: tayruxin/ped#2

**Comment by DonovanJJ** [comment]
Situation: The invalid command format is caused due to the `add` ab3 address book command not being removed
Fix: Removed the `add` command in the application
